services:
    php:
        image: setcms_dev_php:latest
        build:
            context: ./php
        ports:
          - "${NGINX_PORT}:80"
        env_file:
            - ../../.env
        volumes:
            - ../../:/var/www/html