version: "3.3"

services:
    nginx:
        image: setcms_dev_nginx:latest
        build:
            context: ./nginx
        volumes:
            - ../../frontend:/setcms/frontend
        ports:
            - "${NGINX_PORT}:80"
        links:
            - php
    compose:
        build:
            context: ./composer
        volumes:
            - ../../:/setcms
        command: composer.phar install --prefer-dist --no-dev --no-scripts --no-plugins --no-interaction --no-progress
    php:
        image: setcms_dev_php:latest
        build:
            context: ./php
        volumes:
            - ../../:/setcms
    migration_main:
        build:
            context: ./migrations
        volumes:
            - ../../:/setcms
        command: php /setcms/bin/migrations-main.php migrations:migrate --no-interaction
    postgres:
        image: postgres:latest
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_DB: main
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
    adminer:
        image: adminer:latest
        ports:
            - ${ADMINER_PORT}:8080
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        links:
            - postgres