FROM php:7.4-fpm

WORKDIR /app/setcms

RUN apt-get update
RUN apt-get install -y libpng-dev
RUN apt-get install -y nano

RUN docker-php-ext-install gd

RUN php -r "copy('https://getcomposer.org/installer', '/composer-setup.php');" && \
    php /composer-setup.php  --version=1.10.22 --install-dir=/usr/local/bin && \
    php -r "unlink('/composer-setup.php');"

CMD ["php-fpm"]