version: "3.3"

services:
    nginx:
        image: nginx:latest
        ports:
            - 8000:8000
        volumes:
            - ./nginx/:/etc/nginx/conf.d
            - ./../:/app/backend/
        links:
            - php
    php:
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        volumes:
            - ./../:/app/backend/
