<?php

$installer = [
    'post' => [
        'version' => '0.1.1',
        'level' => 'user',
        'lang' => [
            'ru_RU' => [
                'name' => 'Пост',
                'description' => 'Публикация постов',
            ],
        ],
        'required' => [
            'acl' => '>=0.1.1',
            'basic' => '>=0.1.1',
            'migration' => '>=0.1.1',
        ],
        'extends' => [
            'menu',
        ],
        'files' => [
            'Module/Post/Servant/PostDeleteServant.php',
            'Module/Post/Servant/PostSaveServant.php',
            'Module/Post/PostConstrants.php',
            'Module/Post/View/PostPrivateEditView.php',
            'Module/Post/View/PostPrivateReadView.php',
            'Module/Post/View/PostPrivateUpdateView.php',
            'Module/Post/View/PostPrivateNewView.php',
            'Module/Post/View/PostPublicIndexView.php',
            'Module/Post/View/PostPrivateIndexView.php',
            'Module/Post/View/PostPrivateCreateView.php',
            'Module/Post/View/PostPublicReadBySlugView.php',
            'Module/Post/Controller/PostPublicIndexController.php',
            'Module/Post/Controller/PostPublicReadBySlugController.php',
            'Module/Post/Controller/PostPrivateUpdateController.php',
            'Module/Post/Controller/PostPrivateEditController.php',
            'Module/Post/Controller/PostPrivateReadController.php',
            'Module/Post/Controller/PostPrivateCreateController.php',
            'Module/Post/Controller/PostPrivateIndexController.php',
            'Module/Post/Controller/PostPrivateNewController.php',
            'Module/Post/MenuAction/Servant/PostMenuActionsByRequestServant.php',
            'Module/Post/Entity/PostEntity.php',
            'Module/Post/Mapper/PostFromRequestMapper.php',
            'Module/Post/Mapper/PostFromRowMapper.php',
            'Module/Post/Mapper/PostSlugFromRequestMapper.php',
            'Module/Post/Mapper/PostToRowMapper.php',
            'Module/Post/Traits/PostCallTrait.php',
            'Module/Post/Traits/PostDbalDAOTrait.php',
            'Module/Post/Exception/PostNotFoundException.php',
            'Module/Post/Exception/PostMapperNotFoundKeyInRowException.php',
            'Module/Post/Exception/PostException.php',
            'Module/Post/Exception/PostMapperException.php',
            'Module/Post/Exception/PostAlreadyExistsException.php',
            'Module/Post/Exception/PostsNotFoundException.php',
            'Module/Post/Exception/PostExpectOneButReceivedTooMuchException.php',
            'Module/Post/DAO/PostDeleteByIdDAO.php',
            'Module/Post/DAO/PostRetrieveManyByCriteriaDAO.php',
            'Module/Post/DAO/PostCreateDAO.php',
            'Module/Post/DAO/PostHasByIdDAO.php',
            'Module/Post/DAO/PostGetByIdDAO.php',
            'Module/Post/DAO/PostUpdateDAO.php',
            'resources/migrations/sqlite/main/u.20220430204705.posts.sql',
            'resources/migrations/sqlite/main/d.20220430204705.posts.sql',
            'resources/installer/post.php',
            'resources/acl/post.php',
            'resources/exceptionHandlers/post.php',
            'resources/routes/post.php',
            'resources/module/menu/menuActions/post.php',
            'resources/module/menu/adminMenu/post.php',
            'resources/templates/themes/bootstrap5/PostPrivateEdit.twig',
            'resources/templates/themes/bootstrap5/PostPrivateRead.twig',
            'resources/templates/themes/bootstrap5/PostPublicIndex.twig',
            'resources/templates/themes/bootstrap5/PostPublicReadBySlug.twig',
        ],
    ],
];
